name: Gradle CI

on:
  pull_request:
    branches: [ main, dev ]
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: final/Backend  # 모든 run 명령에 대한 기본 작업 디렉토리 설정

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Test with Gradle
        run: |
          ./gradlew test --info
        env:
          API_KEY: ${{ secrets.API_KEY }}
          JWT_KEY: ${{ secrets.JWT_KEY }}


      - name: test report upload
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            /home/runner/work/final-penet/final-penet/final/Backend/build/reports/tests/test/
            /home/runner/work/final-penet/final-penet/final/Backend/build/test-results/test/